[build]
# Esegue build nella sottocartella frontend
base = "frontend"
command = "npm run build"
publish = "build"

[build.environment]
NODE_VERSION = "18"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
