import React, { useState, useEffect } from 'react';
import { generateChapter3Content } from '../utils/chapter3Generator';

/**
 * MEDIUM-1: SustainabilityReportBuilder
 * 
 * Componente per costruire il Bilancio di Sostenibilità con 10 capitoli:
 * - Capitolo 3 auto-generato dai dati di materialità
 * - Altri capitoli editabili manualmente
 * - Sistema upload allegati (immagini/PDF)
 * - Navigazione tra capitoli
 * - Persistenza in audit.reportChapters
 */

const CHAPTER_STRUCTURE = [
    {
        id: 1,
        title: 'Capitolo 1 - Profilo dell\'Organizzazione',
        description: 'Descrizione dell\'azienda, governance, struttura organizzativa',
        editable: true,
    },
    {
        id: 2,
        title: 'Capitolo 2 - Strategia e Modello di Business',
        description: 'Strategia aziendale, modello di business, catena del valore',
        editable: true,
    },
    {
        id: 3,
        title: 'Capitolo 3 - Analisi di Materialità',
        description: 'Generato automaticamente dai dati di materialità (ISO 26000, ESRS, Goal ONU)',
        editable: false,
        autoGenerated: true,
    },
    {
        id: 4,
        title: 'Capitolo 4 - Governance e Gestione dei Rischi',
        description: 'Struttura di governance, gestione rischi ESG, compliance',
        editable: true,
    },
    {
        id: 5,
        title: 'Capitolo 5 - Stakeholder Engagement',
        description: 'Identificazione stakeholder, modalità di coinvolgimento, dialogo',
        editable: true,
    },
    {
        id: 6,
        title: 'Capitolo 6 - Performance Ambientale (E)',
        description: 'Indicatori ambientali: clima, energia, acqua, biodiversità, economia circolare',
        editable: true,
    },
    {
        id: 7,
        title: 'Capitolo 7 - Performance Sociale (S)',
        description: 'Indicatori sociali: lavoratori, comunità, diritti umani, consumatori',
        editable: true,
    },
    {
        id: 8,
        title: 'Capitolo 8 - Performance Governance (G)',
        description: 'Condotta aziendale, etica, anti-corruzione, compliance',
        editable: true,
    },
    {
        id: 9,
        title: 'Capitolo 9 - Obiettivi e Target',
        description: 'Obiettivi di sostenibilità, target quantitativi, roadmap',
        editable: true,
    },
    {
        id: 10,
        title: 'Capitolo 10 - Allegati e Note Metodologiche',
        description: 'Tabelle, grafici, note metodologiche, indice GRI/ESRS',
        editable: true,
    },
];

function SustainabilityReportBuilder({ audit, onUpdate }) {
    const [currentChapterId, setCurrentChapterId] = useState(1);
    const [chapters, setChapters] = useState(audit.reportChapters || {});
    const [attachments, setAttachments] = useState(audit.reportAttachments || {});
    const [isSaving, setIsSaving] = useState(false);
    const [showAttachmentUpload, setShowAttachmentUpload] = useState(false);

    const currentChapter = CHAPTER_STRUCTURE.find(ch => ch.id === currentChapterId);

    // Salva automaticamente quando cambiano i capitoli
    useEffect(() => {
        const timer = setTimeout(() => {
            if (JSON.stringify(audit.reportChapters) !== JSON.stringify(chapters)) {
                saveChapters();
            }
        }, 2000); // Auto-save dopo 2 secondi di inattività

        return () => clearTimeout(timer);
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [chapters]);

    const saveChapters = () => {
        setIsSaving(true);
        onUpdate({
            reportChapters: chapters,
            reportAttachments: attachments,
        });
        setTimeout(() => setIsSaving(false), 500);
    };

    const handleContentChange = (chapterId, content) => {
        setChapters(prev => ({
            ...prev,
            [chapterId]: {
                ...prev[chapterId],
                content,
                lastModified: new Date().toISOString(),
            }
        }));
    };

    const generateChapter3 = () => {
        if (!audit.impactScores || !audit.financialAssessment) {
            alert('⚠️ Dati mancanti! Completa prima:\n- Questionario ISO 26000\n- Analisi Finanziaria\n- Matrice Doppia Materialità');
            return;
        }

        const chapter3Content = generateChapter3Content(audit);
        
        setChapters(prev => ({
            ...prev,
            3: {
                content: chapter3Content,
                autoGenerated: true,
                generatedAt: new Date().toISOString(),
                lastModified: new Date().toISOString(),
            }
        }));

        alert('✅ Capitolo 3 generato automaticamente dai dati di materialità!');
    };

    const handleFileUpload = async (chapterId, event) => {
        const files = Array.from(event.target.files);

        for (const file of files) {
            if (file.size > 10 * 1024 * 1024) { // Max 10MB
                alert(`⚠️ File "${file.name}" troppo grande (max 10MB)`);
                continue;
            }

            const reader = new FileReader();
            reader.onloadend = () => {
                const newAttachment = {
                    name: file.name,
                    type: file.type,
                    size: file.size,
                    data: reader.result,
                    uploadedAt: new Date().toISOString(),
                };

                setAttachments(prev => ({
                    ...prev,
                    [chapterId]: [...(prev[chapterId] || []), newAttachment]
                }));
            };

            if (file.type.startsWith('image/')) {
                reader.readAsDataURL(file);
            } else {
                reader.readAsDataURL(file); // PDF/altri file come data URL
            }
        }

        event.target.value = ''; // Reset input
    };

    const removeAttachment = (chapterId, index) => {
        if (!window.confirm('Rimuovere questo allegato?')) return;

        setAttachments(prev => ({
            ...prev,
            [chapterId]: prev[chapterId].filter((_, i) => i !== index)
        }));
    };

    const exportReport = () => {
        const reportData = {
            metadata: {
                azienda: audit.azienda,
                dimensione: audit.dimensione,
                dataAvvio: audit.dataAvvio,
                exportDate: new Date().toISOString(),
                version: '1.0',
            },
            chapters: CHAPTER_STRUCTURE.map(ch => ({
                id: ch.id,
                title: ch.title,
                content: chapters[ch.id]?.content || '',
                autoGenerated: ch.autoGenerated || false,
                generatedAt: chapters[ch.id]?.generatedAt,
                lastModified: chapters[ch.id]?.lastModified,
                attachments: attachments[ch.id] || [],
            })),
        };

        const blob = new Blob([JSON.stringify(reportData, null, 2)], {
            type: 'application/json',
        });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `bilancio-sostenibilita_${audit.azienda}_${new Date().toISOString().split('T')[0]}.json`;
        a.click();
        URL.revokeObjectURL(url);

        alert('✅ Report esportato come JSON. Usa la funzione "Export Word/PDF" per il documento finale.');
    };

    const getChapterProgress = () => {
        const totalChapters = CHAPTER_STRUCTURE.length;
        const completedChapters = CHAPTER_STRUCTURE.filter(ch => {
            const content = chapters[ch.id]?.content || '';
            return content.trim().length > 100; // Almeno 100 caratteri
        }).length;

        return {
            total: totalChapters,
            completed: completedChapters,
            percentage: Math.round((completedChapters / totalChapters) * 100),
        };
    };

    const progress = getChapterProgress();

    return (
        <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '20px' }}>
            {/* Header */}
            <div
                style={{
                    backgroundColor: '#1976d2',
                    color: 'white',
                    padding: '20px',
                    borderRadius: '8px',
                    marginBottom: '20px',
                }}
            >
                <h1 style={{ margin: '0 0 10px 0' }}>📄 Bilancio di Sostenibilità</h1>
                <p style={{ margin: '0', opacity: 0.9 }}>
                    {audit.azienda} ({audit.dimensione}) - Anno {new Date().getFullYear()}
                </p>
                {isSaving && (
                    <p style={{ margin: '5px 0 0 0', fontSize: '14px', opacity: 0.8 }}>
                        💾 Salvataggio automatico in corso...
                    </p>
                )}
            </div>

            {/* Progress Bar */}
            <div
                style={{
                    backgroundColor: '#f5f5f5',
                    padding: '15px',
                    borderRadius: '8px',
                    marginBottom: '20px',
                }}
            >
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '10px' }}>
                    <span style={{ fontWeight: 'bold' }}>Progresso Completamento</span>
                    <span>
                        {progress.completed}/{progress.total} capitoli ({progress.percentage}%)
                    </span>
                </div>
                <div
                    style={{
                        width: '100%',
                        height: '20px',
                        backgroundColor: '#e0e0e0',
                        borderRadius: '10px',
                        overflow: 'hidden',
                    }}
                >
                    <div
                        style={{
                            width: `${progress.percentage}%`,
                            height: '100%',
                            backgroundColor: progress.percentage === 100 ? '#4caf50' : '#2196f3',
                            transition: 'width 0.3s ease',
                        }}
                    />
                </div>
            </div>

            <div style={{ display: 'flex', gap: '20px', flexWrap: 'wrap' }}>
                {/* Sidebar Navigazione Capitoli */}
                <div style={{ flex: '0 0 300px', minWidth: '250px' }}>
                    <div
                        style={{
                            backgroundColor: '#f8f9fa',
                            padding: '15px',
                            borderRadius: '8px',
                            position: 'sticky',
                            top: '20px',
                        }}
                    >
                        <h3 style={{ margin: '0 0 15px 0', color: '#333' }}>Capitoli</h3>
                        {CHAPTER_STRUCTURE.map(chapter => {
                            const chapterData = chapters[chapter.id];
                            const isCompleted = chapterData?.content?.trim().length > 100;
                            const isCurrent = currentChapterId === chapter.id;

                            return (
                                <button
                                    key={chapter.id}
                                    onClick={() => setCurrentChapterId(chapter.id)}
                                    style={{
                                        width: '100%',
                                        padding: '12px',
                                        marginBottom: '8px',
                                        backgroundColor: isCurrent ? '#1976d2' : 'white',
                                        color: isCurrent ? 'white' : '#333',
                                        border: isCurrent ? 'none' : '1px solid #ddd',
                                        borderRadius: '6px',
                                        cursor: 'pointer',
                                        textAlign: 'left',
                                        fontSize: '14px',
                                        fontWeight: isCurrent ? 'bold' : 'normal',
                                        transition: 'all 0.2s',
                                    }}
                                    onMouseEnter={(e) => {
                                        if (!isCurrent) e.target.style.backgroundColor = '#e3f2fd';
                                    }}
                                    onMouseLeave={(e) => {
                                        if (!isCurrent) e.target.style.backgroundColor = 'white';
                                    }}
                                >
                                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                                        <span>
                                            {isCompleted ? '✅' : chapter.autoGenerated ? '🤖' : '📝'}
                                        </span>
                                        <span>Cap. {chapter.id}</span>
                                    </div>
                                    <div
                                        style={{
                                            fontSize: '12px',
                                            opacity: 0.8,
                                            marginTop: '4px',
                                        }}
                                    >
                                        {chapter.title.replace(`Capitolo ${chapter.id} - `, '')}
                                    </div>
                                </button>
                            );
                        })}

                        <hr style={{ margin: '20px 0', border: 'none', borderTop: '1px solid #ddd' }} />

                        <button
                            onClick={exportReport}
                            style={{
                                width: '100%',
                                padding: '12px',
                                backgroundColor: '#4caf50',
                                color: 'white',
                                border: 'none',
                                borderRadius: '6px',
                                cursor: 'pointer',
                                fontWeight: 'bold',
                                fontSize: '14px',
                            }}
                        >
                            📤 Esporta Report JSON
                        </button>
                    </div>
                </div>

                {/* Editor Capitolo Corrente */}
                <div style={{ flex: '1', minWidth: '500px' }}>
                    <div
                        style={{
                            backgroundColor: 'white',
                            padding: '20px',
                            borderRadius: '8px',
                            border: '1px solid #ddd',
                        }}
                    >
                        {/* Header Capitolo */}
                        <div style={{ marginBottom: '20px' }}>
                            <h2 style={{ margin: '0 0 10px 0', color: '#1976d2' }}>
                                {currentChapter.title}
                            </h2>
                            <p style={{ margin: '0', color: '#666', fontSize: '14px' }}>
                                {currentChapter.description}
                            </p>
                            {currentChapter.autoGenerated && (
                                <div
                                    style={{
                                        marginTop: '10px',
                                        padding: '10px',
                                        backgroundColor: '#fff3cd',
                                        border: '1px solid #ffc107',
                                        borderRadius: '4px',
                                        fontSize: '14px',
                                    }}
                                >
                                    🤖 <strong>Capitolo Auto-Generato</strong>
                                    <br />
                                    Questo capitolo viene creato automaticamente dai dati di materialità.
                                    <button
                                        onClick={generateChapter3}
                                        style={{
                                            marginLeft: '10px',
                                            padding: '5px 10px',
                                            backgroundColor: '#ff9800',
                                            color: 'white',
                                            border: 'none',
                                            borderRadius: '4px',
                                            cursor: 'pointer',
                                            fontSize: '13px',
                                        }}
                                    >
                                        🔄 Rigenera Contenuto
                                    </button>
                                </div>
                            )}
                        </div>

                        {/* Editor Contenuto */}
                        <div style={{ marginBottom: '20px' }}>
                            <label
                                style={{
                                    display: 'block',
                                    fontWeight: 'bold',
                                    marginBottom: '8px',
                                    color: '#333',
                                }}
                            >
                                Contenuto del Capitolo
                            </label>
                            <textarea
                                value={chapters[currentChapterId]?.content || ''}
                                onChange={(e) =>
                                    handleContentChange(currentChapterId, e.target.value)
                                }
                                placeholder={
                                    currentChapter.autoGenerated
                                        ? 'Clicca "Rigenera Contenuto" per generare automaticamente questo capitolo...'
                                        : 'Scrivi il contenuto del capitolo qui...'
                                }
                                disabled={currentChapter.autoGenerated && !chapters[currentChapterId]?.content}
                                style={{
                                    width: '100%',
                                    minHeight: '400px',
                                    padding: '12px',
                                    fontSize: '14px',
                                    lineHeight: '1.6',
                                    border: '1px solid #ddd',
                                    borderRadius: '4px',
                                    fontFamily: 'inherit',
                                    resize: 'vertical',
                                }}
                            />
                            <div
                                style={{
                                    marginTop: '8px',
                                    fontSize: '12px',
                                    color: '#666',
                                    display: 'flex',
                                    justifyContent: 'space-between',
                                }}
                            >
                                <span>
                                    {(chapters[currentChapterId]?.content || '').length} caratteri
                                </span>
                                {chapters[currentChapterId]?.lastModified && (
                                    <span>
                                        Ultima modifica:{' '}
                                        {new Date(chapters[currentChapterId].lastModified).toLocaleString('it-IT')}
                                    </span>
                                )}
                            </div>
                        </div>

                        {/* Allegati */}
                        <div>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                                <label style={{ fontWeight: 'bold', color: '#333' }}>
                                    📎 Allegati ({(attachments[currentChapterId] || []).length})
                                </label>
                                <button
                                    onClick={() => setShowAttachmentUpload(!showAttachmentUpload)}
                                    style={{
                                        padding: '6px 12px',
                                        backgroundColor: '#2196f3',
                                        color: 'white',
                                        border: 'none',
                                        borderRadius: '4px',
                                        cursor: 'pointer',
                                        fontSize: '13px',
                                    }}
                                >
                                    {showAttachmentUpload ? '✖ Chiudi' : '➕ Aggiungi Allegato'}
                                </button>
                            </div>

                            {showAttachmentUpload && (
                                <div
                                    style={{
                                        padding: '15px',
                                        backgroundColor: '#f5f5f5',
                                        borderRadius: '6px',
                                        marginBottom: '15px',
                                    }}
                                >
                                    <input
                                        type="file"
                                        accept="image/*,.pdf,.doc,.docx,.xls,.xlsx"
                                        multiple
                                        onChange={(e) => handleFileUpload(currentChapterId, e)}
                                        style={{
                                            width: '100%',
                                            padding: '8px',
                                            border: '2px dashed #2196f3',
                                            borderRadius: '4px',
                                            backgroundColor: 'white',
                                        }}
                                    />
                                    <p style={{ margin: '8px 0 0 0', fontSize: '12px', color: '#666' }}>
                                        Formati supportati: immagini, PDF, Word, Excel (max 10MB per file)
                                    </p>
                                </div>
                            )}

                            {/* Lista Allegati */}
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '10px' }}>
                                {(attachments[currentChapterId] || []).map((attachment, index) => (
                                    <div
                                        key={index}
                                        style={{
                                            padding: '10px',
                                            backgroundColor: '#f8f9fa',
                                            border: '1px solid #ddd',
                                            borderRadius: '6px',
                                            width: attachment.type.startsWith('image/') ? '150px' : '100%',
                                        }}
                                    >
                                        {attachment.type.startsWith('image/') ? (
                                            <img
                                                src={attachment.data}
                                                alt={attachment.name}
                                                style={{
                                                    width: '100%',
                                                    height: '100px',
                                                    objectFit: 'cover',
                                                    borderRadius: '4px',
                                                    marginBottom: '8px',
                                                }}
                                            />
                                        ) : (
                                            <div
                                                style={{
                                                    padding: '20px',
                                                    backgroundColor: '#e3f2fd',
                                                    borderRadius: '4px',
                                                    textAlign: 'center',
                                                    marginBottom: '8px',
                                                }}
                                            >
                                                📄
                                            </div>
                                        )}
                                        <div style={{ fontSize: '12px', wordBreak: 'break-word' }}>
                                            <strong>{attachment.name}</strong>
                                            <br />
                                            <span style={{ color: '#666' }}>
                                                {(attachment.size / 1024).toFixed(1)} KB
                                            </span>
                                        </div>
                                        <button
                                            onClick={() => removeAttachment(currentChapterId, index)}
                                            style={{
                                                width: '100%',
                                                marginTop: '8px',
                                                padding: '4px',
                                                backgroundColor: '#f44336',
                                                color: 'white',
                                                border: 'none',
                                                borderRadius: '4px',
                                                cursor: 'pointer',
                                                fontSize: '12px',
                                            }}
                                        >
                                            🗑️ Rimuovi
                                        </button>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Navigazione Capitoli */}
                        <div
                            style={{
                                marginTop: '30px',
                                paddingTop: '20px',
                                borderTop: '1px solid #ddd',
                                display: 'flex',
                                justifyContent: 'space-between',
                            }}
                        >
                            <button
                                onClick={() => setCurrentChapterId(Math.max(1, currentChapterId - 1))}
                                disabled={currentChapterId === 1}
                                style={{
                                    padding: '10px 20px',
                                    backgroundColor: currentChapterId === 1 ? '#ccc' : '#2196f3',
                                    color: 'white',
                                    border: 'none',
                                    borderRadius: '4px',
                                    cursor: currentChapterId === 1 ? 'not-allowed' : 'pointer',
                                    fontWeight: 'bold',
                                }}
                            >
                                ⬅️ Capitolo Precedente
                            </button>
                            <button
                                onClick={saveChapters}
                                style={{
                                    padding: '10px 20px',
                                    backgroundColor: '#4caf50',
                                    color: 'white',
                                    border: 'none',
                                    borderRadius: '4px',
                                    cursor: 'pointer',
                                    fontWeight: 'bold',
                                }}
                            >
                                💾 Salva Manualmente
                            </button>
                            <button
                                onClick={() => setCurrentChapterId(Math.min(10, currentChapterId + 1))}
                                disabled={currentChapterId === 10}
                                style={{
                                    padding: '10px 20px',
                                    backgroundColor: currentChapterId === 10 ? '#ccc' : '#2196f3',
                                    color: 'white',
                                    border: 'none',
                                    borderRadius: '4px',
                                    cursor: currentChapterId === 10 ? 'not-allowed' : 'pointer',
                                    fontWeight: 'bold',
                                }}
                            >
                                Capitolo Successivo ➡️
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default SustainabilityReportBuilder;
