name: CI

on:
  push:
    branches: [restore-76d4866, main, master]
  pull_request:
    branches: [restore-76d4866, main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --ci --watchAll=false

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: frontend/build
          if-no-files-found: error

      - name: Install Playwright Browsers
        working-directory: ./frontend
        run: npx playwright install --with-deps

      - name: Run E2E tests (Playwright)
        working-directory: ./frontend
        env:
          CI: "true"
        run: npx playwright test --reporter=html

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          if-no-files-found: warn

  # Lint stage placeholder (enable when eslint script is added)
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 18
  #         cache: 'npm'
  #     - name: Install deps
  #       working-directory: ./frontend
  #       run: npm ci
  #     - name: Run ESLint
  #       working-directory: ./frontend
  #       run: npm run lint
